accounts/urls.py
from django.conf import settings
from django.conf.urls import url

from .views import (
        client_registration,
        auth_login,
        auth_logout,
        pharmacy_registration,
        bridge,
        )

urlpatterns = [
    url(r'^inscription', client_registration, name='inscription-normale'),
    url(r'^identification', auth_login, name='login'),
    url(r'^deconnection', auth_logout, name='logout'),
    url(r'^pharmacie', pharmacy_registration, name='new_pharmacy'),
    url(r'^choix', bridge, name='account_choice'),
]

medicaments/urls.py
from django.conf import settings
from django.conf.urls import url, include

from .models import Medicament

from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken.views import obtain_auth_token

from .views import (
    home,
    # create_medicament,
    update_medicament,
    MedicamentCreate,
    MedicamentDetail,
    MedicamentDelete,
    public_med_list,
    personal_med_list,
    CreateView,
    DetailsView
    )

urlpatterns = [
    url(r'^ajouter', MedicamentCreate.as_view(), name="ajouter"),
    url(r'^delete/(?P<pk>\d+)/$', MedicamentDelete.as_view(), name='delete'),
    url(r'^modifier/(?P<pk>\d+)/$', update_medicament, name="modifier"),
    url(r'^medicaments', public_med_list, name="liste-publique"),
    url(r'^inventaire', personal_med_list, name='inventaire'),
    url(r'^item/(?P<pk>\d+)/$', MedicamentDetail.as_view(), name='detail'),
    # url(r'^newmeds/$', CreateView.as_view(), name='create'),
    # url(r'^newmeds/(?P<pk>[0-9]+)/$', DetailsView.as_view(), name="details"),
    # url(r'^get-token/', obtain_auth_token),
]

# urlpatterns = format_suffix_patterns(urlpatterns)

pharmaonline_beta/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin



urlpatterns = [
    url(r'^api/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', 'general.views.landing', name='accueil'),
    url(r'^dashboard', 'general.views.dashboard', name='dashboard'),
    url(r'^about-us', 'general.views.about', name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls')),
    url(r'^comptes/', include("accounts.urls", namespace="accounts")),
    url(r'^medicaments/', include("medicaments.urls", namespace="medicaments")),
    url(r'^contact/', include("contact_us.urls", namespace="contact_us")),
    url(r'^api/', include('medicaments.rest_urls', namespace="rest_urls"))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

from django.core.validators import RegexValidator

# Create your models here.
class PharmacyUserManager(BaseUserManager):
    def create_user(self, name=None, email=None, password=None):
        """
        Creates and saves a User with the given name, email and password.
        """
        if not name:
        	raise ValueError('Ce champ doit contenir le name de votre pharmacie')
        if not email:
            raise ValueError('Vous devez fournir une adresse email valide.')

        user = self.model(
        	name = name,
            email = self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, name, email,  password):
        """
        Creates and saves a superuser with the given username, email and password.
        """

        user = self.create_user(
			name=name,
			email=email,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class PharmacyUser(AbstractBaseUser):
    type_choices = (
        ('SS', 'Sharprise Staff'),
        ('P', 'Pharmacy'),
        ('N', 'Normal Account'),
    )
    user_type = models.CharField(
        max_length=2,
        choices=type_choices,
        default='C',
    )
    name = models.CharField(
        max_length=255,
        unique=True,
	)
    email = models.EmailField(
	    verbose_name='email address',
	    max_length=255,
	    unique=True,
	)
    owner_first_name = models.CharField(
        max_length=120,
        null=True,
        blank=True,
    )
    owner_last_name = models.CharField(
        max_length=120,
        null=True,
        blank=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = PharmacyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        # The user is identified by their email address
        return "%s %s" %(self.owner_first_name, self.owner_last_name)

    def get_short_name(self):
	    # The user is identified by their email address
        return self.owner_first_name

    def __str__(self):
        return self.name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

class SharpriseStaff(models.Model):
    user = models.OneToOneField(PharmacyUser)


class Pharmacy(models.Model):
    user = models.OneToOneField(PharmacyUser)
    addresse = models.CharField(max_length=255, blank=True)
    proprietaire = models.CharField(max_length=255, blank=True)
    horaire = models.TextField()
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(max_length=30, validators=[phone_regex], blank=True) # validators should be a list


class NormalUser(models.Model):
    user = models.OneToOneField(PharmacyUser)

class Agency(models.Model):
    user = models.OneToOneField(PharmacyUser)
    address = models.CharField(max_length=255, blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(max_length=30, validators=[phone_regex], blank=True) # validators should be a list

accounts/forms.py
from django import forms
from .models import PharmacyUser, Pharmacy, NormalUser

from django.core.validators import RegexValidator



def has_number(string):
    return any(char.isdigit() for char in string)

def has_upper(string):
    return any(char.isupper() for char in string)


class AdminRegistration(forms.ModelForm):

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = PharmacyUser
        fields = ['name', 'email', 'password']

    def clean_password(self):
        password1 = self.cleaned_data.get("password1")

        if len(password1) < 7:
            raise forms.ValidationError("Mot de Passe trop court.")

        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Les mots de passe ne concordent pas.")

        return password2

    def clean_name(self):
        name = self.cleaned_data.get('name')
        try:
            exists = PharmacyUser.objects.get(name=name)
            raise forms.ValidationError("This Pharmacy Already Exists.")
        except PharmacyUser.DoesNotExist:
                return(name)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            exists = PharmacyUser.objects.get(email=email)
            raise forms.ValidationError("This email is already in use.")
        except PharmacyUser.DoesNotExist:
            return email

    def save(self, commit=True):
        user = super(AdminRegistration, self).save(commit=False)
        user.set_password(self.cleaned_data.get["password1"])
        if commit:
            user.save()
        return user

class CreateUser(forms.ModelForm):

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = PharmacyUser
        fields = ['name', 'email', 'password']

    def clean_password(self):
        password1 = self.cleaned_data.get("password1")

        if len(password1) < 7:
            raise forms.ValidationError("Mot de Passe trop court.")

        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Les mots de passe ne concordent pas.")

        return password2

    def clean_name(self):
        name = self.cleaned_data.get('name')
        try:
            exists = PharmacyUser.objects.get(name=name)
            raise forms.ValidationError("This Pharmacy Already Exists.")
        except PharmacyUser.DoesNotExist:
                return(name)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            exists = PharmacyUser.objects.get(email=email)
            raise forms.ValidationError("This email is already in use.")
        except PharmacyUser.DoesNotExist:
            return email

    def save(self, commit=True):
        user = super(CreateUser, self).save(commit=False)
        user.set_password(self.cleaned_data.get["password1"])
        if commit:
            user.save()
        return user


SCHEDULE_CHOICES = (
    ('lundi', 'Lundi'),
    ('mardi', 'Mardi'),
    ('mercredi', 'Mercredi'),
    ('jeudi', 'Jeudi'),
    ('vendredi', 'Vendredi'),
    ('samedi', 'Samedi'),
    ('dimanche', 'Dimanche'),
)


class RegistrationForm(forms.Form):
    name  = forms.CharField(label="Entrez votre nom complet")
    email = forms.EmailField(label="Entrez votre adresse email")
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput())
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput())

    def clean_password(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 6:
            raise forms.ValidationError("Password must contain at least 6 characters.")
        if not (has_upper(password1) or has_number(password1)):
            raise forms.ValidationError("Password must contain at least: 1 uppercase letter and 1 number. Try again.")
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("The passwords you have entered do not match.")
        return password1

    def clean_name(self):
        name = self.cleaned_data.get('name')
        try:
            exists = PharmacyUser.objects.get(name=name)
            raise forms.ValidationError("This Pharmacy Already Exists.")
        except PharmacyUser.DoesNotExist:
                return(name)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            exists = PharmacyUser.objects.get(email=email)
            raise forms.ValidationError("This email is already in use.")
        except PharmacyUser.DoesNotExist:
            return email


class PharmacyRegistrationForm(forms.ModelForm):
    """A form for creating Pharmacies. Has to be used in tandem with the
    standard RegistrationForm."""
    horaire =  forms.CharField(label="Your pharmacy's schedule.", widget=forms.Textarea)

    class Meta:
        model = Pharmacy
        exclude = ['user']

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(PharmacyRegistrationForm, self).save(commit=False)
        if commit:
            user.save()
        return user


    def clean_password(self):
        password1 = self.cleaned_data.get('password1')
        if len(password1) < 6:
            raise forms.ValidationError("Password must contain at least 6 characters.")
        #if (password1.islower() or password1.isdigit()):
        #    raise forms.ValidationError("Password must contain at least: n\
        #    1 uppercase letter and 1 number. Try again.")
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("The passwords you have entered do not match.")
        return password1

    def clean_name(self):
        name = self.cleaned_data.get('name')
        try:
            exists = PharmacyUser.objects.get(name=name)
            raise forms.ValidationError("This Pharmacy Already Exists.")
        except PharmacyUser.DoesNotExist:
                return(name)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            exists = PharmacyUser.objects.get(email=email)
            raise forms.ValidationError("This email is already in use.")
        except PharmacyUser.DoesNotExist:
            return email


class LoginForm(forms.Form):
    email = forms.CharField(label="Email")
    password = forms.CharField(label="Password", widget=forms.PasswordInput())

accounts/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.core.mail import send_mail, BadHeaderError

from .forms import RegistrationForm, LoginForm, CreateUser, PharmacyRegistrationForm
from .models import PharmacyUser, Pharmacy, NormalUser


# Create your views here.
def client_registration(request):
    """ Simple registration view for new clients. """
    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password1']
        new_user = PharmacyUser()
        new_user.name = name
        new_user.email = email
        new_user.set_password(password)
        new_user.save()

        messages.success(request, "Bienvenue %s" %(request.user))
        return redirect("/")
    else:
        form = RegistrationForm(request.POST or None)
    next_url = "/"
    context = {
        "form": form,
        "next_url": next_url,
    }
    return render(request, 'accounts/account_register.html', context)

def pharmacy_registration(request):
    """An updated registration form, specifically for pharmacies."""
    pharmacy_form = PharmacyRegistrationForm(request.POST or None)
    register_form = RegistrationForm(request.POST or None)
    if register_form.is_valid() and pharmacy_form.is_valid():
        name = register_form.cleaned_data['name']
        email = register_form.cleaned_data['email']
        password = register_form.cleaned_data['password1']
        new_user = PharmacyUser()
        new_user.name = name
        new_user.email = email
        new_user.set_password(password)
        new_user.save()
        pharmacy = pharmacy_form.save(commit=False)
        pharmacy.user = new_user
        pharmacy.adresse = adresse
        pharmacy.horaire = horaire
        pharmacy.proprietaire = proprietaire
        pharmacy.save()
        return redirect('/')
    context = {
        "register_form": register_form,
        "pharmacy_form": pharmacy_form,
    }
    return render(request, "accounts/pharmacy_register.html", context)

def bridge(request):
    return render(request, 'accounts/account_pre_registration.html')

def auth_login(request):
	form = LoginForm(request.POST or None)
	next_url = request.GET.get('next')
	if form.is_valid():
		email = form.cleaned_data['email']
		password = form.cleaned_data['password']
		user = authenticate(email=email, password=password)
		if user is not None:
			login(request, user)
			if next_url is not None:
				return HttpResponseRedirect(next_url)
			return HttpResponseRedirect("/")

	title = "Login"
	submit_btn = title
	submit_btn_class = "btn-success btn-block"
	context = {
		"form": form,
		"title": title,
		"submit_btn": submit_btn,
		"submit_btn_class": submit_btn_class,
		}
	return render(request, "accounts/account_login.html", context)

def auth_logout(request):
    logout(request)
    messages.info(request, "Vous vous etes deconnectes avec succes.")
    return HttpResponseRedirect(reverse('accounts:login'))



def send_email(request):
    subject = request.POST.get('subject', '')
    message = request.POST.get('message', '')
    from_email = request.POST.get('from_email', '')
    if subject and message and from_email:
        try:
            send_mail(subject, message, from_email, ['admin@example.com'])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return HttpResponseRedirect('/contact/thanks/')
    else:
        # In reality we'd use a form class
        # to get proper validation errors.
        return HttpResponse('Make sure all fields are entered and valid.')

templates/accounts/account_base.html
<!DOCTYPE html>
<html lang="fr">
{% load staticfiles %}


  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Henri E. Francois" />
    <title>{% block title %} PharmaOnline | Bienvenue {% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/freelancer.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}" />



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

  </head>


  <body id="page-top" class="index">
    <nav class="navbar navbar-default navbar-fixed-to-top">
      <div class='container-fluid'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'accueil' %}">
            <img alt="Brand" src="{% static "img/quick-pharma-logo.png" %}" height="120%" width="30px">
          </a>
        </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'medicaments:liste-publique' %}">Medicaments</a></li>
              <li class="disabled"><a href="#">Carte</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <!--li><a href="#">Link</a></li>-->
              {% if request.user.is_authenticated %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mon Compte <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li class="text-center"><a href="{% url 'medicaments:ajouter' %}"> Ajouter des Medicaments </a></li>
                  <li class="text-center"><a href="{% url 'medicaments:inventaire' %}"> Modifier les Medicaments </a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="https://medoc.herokuapp.com">Aller a MeDOC</a></li>
                  <li><a href="{% url 'accounts:logout' %}">Se deconnecter</a></li>
                </ul>
              </li>
              {% else %}
              <li><a href="{% url 'accounts:login' %}">login</a></li>
              <li><a href="{% url 'accounts:account_choice' %}">Register</a></li>
              {% endif %}
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      {% block content %}
      {% endblock %}
      <!-- Footer -->
<!--      <footer class="footer text-center">
          <div class="footer-above">
              <div class="container">
                  <div class="row">
                      <div class="footer-col col-md-4">
                          <h3>Retrouvez-nous</h3>
                          <p>Institution Saint-Louis de Gonzague , Delmas 31-33</p>
                      </div>
                      <div class="footer-col col-md-4">
                          <h3>Autour du Web</h3>
                          <ul class="list-inline">
                              <li>
                                  <a href="https://www.facebook.com/pharmaon" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                              </li>
                              <li>
                                  <a href="htpps://www.twitter.com" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                              </li>
                          </ul>
                      </div>
                      <div class="footer-col col-md-4">
                          <h3>A propos de P.O.</h3>
                          <p>Commentaires? Envoyez-nous un mail: exemple@gmail.com </p>
                          <p>Ou essayez par notre <a href="#">Page de Contact</a> </p>
                      </div>
                  </div>
              </div>
          </div>
          <div class="footer-below">
              <div class="container">
                  <div class="row">
                      <div class="col-lg-12">
                          Copyright &copy; PharmaOnline 2016
                      </div>
                  </div>
              </div>
          </div>
      </footer> -->
      <div class="scroll-top page-scroll visible-xs visible-sm">
          <a class="btn btn-primary" href="#page-top">
              <i class="fa fa-chevron-up"></i>
          </a>
      </div>
  </body>


      <!-- jQuery -->
      <script src="{% static 'js/jquery.js' %}"></script>

      <!-- Bootstrap Core JavaScript -->
      <script src="{% static 'js/bootstrap.min.js' %}"></script>

templates/accounts/account_login.html
{% extends 'medicaments/med_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="row">
     <div class="col-sm-6 col-sm-offset-3">
       <div class="panel"><p><i> Bienvenue, veuillez saisir votre adresse e-mail et votre mot de passe</i></p></div>

       <form class="form-horizontal form-control-static" method='POST' action="{{ action_url }}">
         {% csrf_token %}{{ form|crispy }}
         <input class="btn btn-block btn-primary" type="Submit" value="Sign In" />
         <p>Si vous n'avez pas de compte,vous pouvez <a href="{% url 'accounts:account_choice' %}">En creer un en cliquant ici</a> </p>
       </form>

     </div>
  </div>
{% endblock %}

templates/accounts/account_logout.html
{% extends 'medicaments/med_base.html' %}

{% block content %}

  <div>
    <p> Vous etes maintenant deconnectes. </p>
    <p> Voulez vous vous <a href='{% url 'login' %}'>connecter</a> ? </p>
  </div>

templates/accounts/account_pre_registration.html
{% extends 'medicaments/med_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="{% url 'accueil' %}">Summary</a></li>
            <li role="presentation" class="disabled"><a href="#">Pharmacies</a></li>
            <li role="presentation" class="disabled"><a href="#">Individuals</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">PharmaOnline</h3>
      </div>

      <div class="jumbotron">
        <h1>A solution to the Pharmacy Crisis.</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>The Pharmacy</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo,<br> tortor mauris  condimentum nibh, ut fermentum massa justo <br> sit amet risus.</p>
          <a class="btn btn-primary" href="{% url 'accounts:new_pharmacy' %}">new pharmacy</a>
        </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>The Client</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo,<br> tortor mauris  condimentum nibh, ut fermentum massa justo <br> sit amet risus.</p>
          <a class="btn btn-success" href="{% url 'accounts:inscription-normale' %}">New client</a>
        </div>
      </div>

</div> <!-- /container -->



{% endblock %}

templates/accounts/account_register.html
{% extends 'medicaments/med_base.html' %}
{% load crispy_forms_tags %}

{% block content %}



   <div class="col-sm-6 col-sm-offset-3">

     <form class="form-horizontal form-control-static" method='POST' action="{{ action_url }}">
       {% csrf_token %}{{ form|crispy }}
       <button class="btn btn-primary" type="{{ submit_button }}">Creer un Compte</button>
     </form>

   </div>

{% endblock %}

templates/accounts/logged_out.html
{% extends 'medicaments/med_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <p>You have been successfully logged out of your account</p>
  <p>Log in?</p>

{% endblock %}

templates/accounts/pharmacy_register.html
  {% extends 'medicaments/med_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

   <div class="col-sm-6 col-sm-offset-3">

     <form class="form-horizontal form-control-static" method='POST' action="{{ action_url }}">
       {% csrf_token %}{{ register_form | crispy }}
       {{ pharmacy_form | crispy }}
       <input class="btn btn-block btn-primary" type="{{ submit_button }}">Creer un compte</input>
     </form>

   </div>

{% endblock %}