accounts/urls.py
from django.conf import settings
from django.conf.urls import url

from .views import (
        client_registration,
        auth_login,
        auth_logout,
        pharmacy_registration,
        bridge,
        )

urlpatterns = [
    url(r'^inscription', client_registration, name='inscription-normale'),
    url(r'^identification', auth_login, name='login'),
    url(r'^deconnection', auth_logout, name='logout'),
    url(r'^pharmacie', pharmacy_registration, name='new_pharmacy'),
    url(r'^choix', bridge, name='account_choice'),
]

medicaments/urls.py
from django.conf import settings
from django.conf.urls import url, include

from .models import Medicament

from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken.views import obtain_auth_token

from .views import (
    home,
    # create_medicament,
    update_medicament,
    MedicamentCreate,
    MedicamentDetail,
    MedicamentDelete,
    public_med_list,
    personal_med_list,
    CreateView,
    DetailsView
    )

urlpatterns = [
    url(r'^ajouter', MedicamentCreate.as_view(), name="ajouter"),
    url(r'^delete/(?P<pk>\d+)/$', MedicamentDelete.as_view(), name='delete'),
    url(r'^modifier/(?P<pk>\d+)/$', update_medicament, name="modifier"),
    url(r'^medicaments', public_med_list, name="liste-publique"),
    url(r'^inventaire', personal_med_list, name='inventaire'),
    url(r'^item/(?P<pk>\d+)/$', MedicamentDetail.as_view(), name='detail'),
    # url(r'^newmeds/$', CreateView.as_view(), name='create'),
    # url(r'^newmeds/(?P<pk>[0-9]+)/$', DetailsView.as_view(), name="details"),
    # url(r'^get-token/', obtain_auth_token),
]

# urlpatterns = format_suffix_patterns(urlpatterns)

pharmaonline_beta/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin



urlpatterns = [
    url(r'^api/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', 'general.views.landing', name='accueil'),
    url(r'^dashboard', 'general.views.dashboard', name='dashboard'),
    url(r'^about-us', 'general.views.about', name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls')),
    url(r'^comptes/', include("accounts.urls", namespace="accounts")),
    url(r'^medicaments/', include("medicaments.urls", namespace="medicaments")),
    url(r'^contact/', include("contact_us.urls", namespace="contact_us")),
    url(r'^api/', include('medicaments.rest_urls', namespace="rest_urls"))
]

medicaments/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.conf import settings
from django.core.urlresolvers import reverse
from rest_framework.authtoken.models import Token

from accounts.models import Pharmacy

from django.utils.text import slugify
# Create your models here.

class Famille(models.Model):
    nom         = models.CharField(max_length= 255)
    description = models.TextField()

    def __str__(self):
        return self.nom

class Compagnie(models.Model):
    nom  = models.CharField(max_length= 255)
    pays = models.CharField(max_length= 255, blank=True)

    def __str__(self):
        return self.nom

class Medicament(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    commercial  = models.CharField(max_length= 255)
    generique   = models.CharField(max_length= 255)
    quantite    = models.CharField(max_length= 255)
    description = models.TextField()
    stock       = models.IntegerField()
    slug        = models.SlugField(blank=True, null=True)
    famille     = models.ForeignKey('Famille', blank=True, null=True)
    compagnie   = models.ForeignKey('Compagnie', blank=True, null=True)
    statut      = models.CharField(max_length= 255)
    verified    = models.DateTimeField(auto_now=True, auto_now_add=False)
    image       = models.ImageField(blank=True, null=True, upload_to="drug_labels")

    def __str__(self):
        return self.commercial

    def get_absolute_url(self):
        return reverse('medicaments:detail', kwargs={'pk': self.pk})

    def get_modification_url(self):
        return reverse('medicaments:modifier', kwargs={'pk': self.pk})

    def get_deletion_url(self):
        return reverse('medicaments:delete', kwargs={'pk': self.pk})

    def last_seen(self):
        return ("Modifie pour la derniere fois le: %s" %(self.verified))

def create_slug(instance, new_slug=None):
    slug = slugify(instance.commercial + '-' + instance.generique)
    if new_slug is not None:
        slug = new_slug
    qs = Medicament.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=slug)
    return slug


def medicament_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.stock == 0:
        instance.statut = "Medicament en rupture de Stock"
    elif (instance.stock <= 5):
        instance.statut = "Peu d'unites disponibles"
    else:
        instance.statut = "Medicament en Stock"


pre_save.connect(medicament_pre_save_receiver, sender=Medicament)

@receiver(post_save, sender=Pharmacy)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

medicaments/forms.py
from django import forms
from .models import Medicament, Famille, Compagnie

class MedicamentForm(forms.ModelForm):
    commercial= forms.CharField(label="Nom commercial du produit")
    generique = forms.CharField(label="Nom generique du produit")
    quantite  = forms.CharField(label="Contenu de l'unite")
    description = forms.CharField(label="Decrivez le produit", widget=forms.Textarea)
    stock     = forms.CharField(label="Grandeur de votre stock en ce produit")

    class Meta:
        model = Medicament
        fields = [
        'commercial',
        'generique',
        'quantite',
        'description',
        'famille',
        'stock',
        'image',
         ]
    def clean_commercial(self):
        commercial = self.cleaned_data.get('commercial')
        if len(commercial) <= 3:
            raise forms.ValidationError('Le nom du produit est trop court.')
        else:
            return commercial

    def clean_generique(self):
        generique = self.cleaned_data.get('generique')
        if len(generique) <= 3:
            raise forms.ValidationError('Le nom du produit est trop court.')
        else:
            return generique

    def clean_quantite(self):
        quantite = self.cleaned_data.get('quantite')
        if not quantite:
            raise forms.ValidationError("Entrez la quantite (masse/volume/comprimes) de medicament Disponible dans chaque unite")
        else:
            return quantite

    def clean_stock(self):
        stock = self.cleaned_data.get('stock')
        if  not stock:
            raise forms.ValidationError("Veuillez entrer la quantite de medicaments disponibles")
        else:
            return stock

class FamilleForm(forms.ModelForm):
    class Meta:
        model = Famille
        fields = ['nom', 'description']

    def clean_nom(self):
        nom = self.cleaned_data.get('nom')
        if not nom:
            raise forms.ValidationError("Veuillez entrer le nom de la famille de pharmaceutiques")
        else:
            return nom

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if not description:
            raise forms.ValidationError("Veuillez entrer une description de la famille")
        if len(description) < 10:
            raise forms.ValidationError("Description trop courte")
        else:
            return description

class CompagnieForm(forms.ModelForm):
    class Meta:
        model = Compagnie
        fields = ['nom', 'pays']

    def clean_nom(self):
        nom = self.cleaned_data.get('nom')
        if not nom:
            raise forms.ValidationError("Veuillez entrer le nom de la famille de pharmaceutiques")
        else:
            return nom

    def clean_pays(self):
        pays = self.cleaned_data.get('pays')
        if not pays:
            raise forms.ValidationError("Veuillez entrer un pays")
        else:
            return pays

medicaments/views.py
#django
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse_lazy


from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from rest_framework import generics, permissions

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

#other apps
from accounts.models import PharmacyUser

#third-party apps
from haystack.forms import SearchForm
from haystack.generic_views import SearchView

#medicaments
from .models import Medicament, Famille, Compagnie
from .forms import MedicamentForm
from .serializers import MedicamentSerializer
from .permissions import IsOwner

def home(request):
    form = SearchForm
    template = 'medicaments/med_base.html'
    context = {
        "form": form,
        "Submit-btn": "Rechercher",
    }
    return render(request, template, context)

#class ResultView(SearchView):
#    template_name = 'medicaments/results.html'

#MEDICAMENTS
#Vues de Creation et de modification

# @login_required
# def create_medicament(request):
#     form = MedicamentForm(request.POST or None)
#     if form.is_valid():
#         medicament = form.save(commit=False)
#         medicament.user = request.user
#         medicament.save()
#
#         messages.success(request, "Medicament ajoute.")
#     template = "medicaments/med_create.html"
#     context = {
#         "form": form,
#     }
#     return render(request, template, context)

@login_required
def update_medicament(request, pk=None):
    instance = get_object_or_404(Medicament, pk=pk)
    form = MedicamentForm(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.info(request, "Le medicament a ete modifie.")
        return HttpResponseRedirect(instance.get_absolute_url())
    template = "medicaments/med_update.html"
    context = {
        "form": form,
        "instance": instance,
    }
    return render(request, template, context)

def public_med_list(request):
    queryset = Medicament.objects.all()
    paginator = Paginator(queryset, 10)
    template = "medicaments/public_list.html"

    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        "queryset": queryset,
    }
    return render(request, template, context)


@login_required
def personal_med_list(request):
    queryset = Medicament.objects.filter(user= request.user)
    template = "medicaments/private_list.html"
    context = {
        "queryset": queryset,
    }
    return render(request, template, context)


#vues des elements individuellement
class MedicamentDetail(DetailView):
    model = Medicament
    template_name = "medicaments/med_detail.html"


#vues de suppression
class MedicamentDelete(DeleteView):
    model = Medicament
    success_url = reverse_lazy('inventaire')

class MedicamentCreate(CreateView):
    model = Medicament
    # fields = ('commercial', 'generique', 'quantite', 'description', 'famille', 'stock', 'image')
    success_url = reverse_lazy('ajouter')
    form_class = MedicamentForm
    template_name = 'medicaments/med_create.html'

class CreateView(generics.ListCreateAPIView):
    queryset = Medicament.objects.all()
    serializer_class = MedicamentSerializer
    permission_class = (permissions.IsAuthenticated, IsOwner)

    def perform_create(self, serializer):
        """Save the post data when creating a new bucketlist."""
        serializer.save(user=self.request.user)


class DetailsView(generics.RetrieveUpdateDestroyAPIView):
    """This class handles the http GET, PUT and DELETE requests."""

    queryset = Medicament.objects.all()
    serializer_class = MedicamentSerializer
    permission_class = (permissions.IsAuthenticated, IsOwner)

templates/medicaments/med_base.html
<!DOCTYPE html>
<html lang="fr">
{% load staticfiles %}


  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Henri E. Francois" />
    <title>{% block title %}PharmaOnline | Bienvenue {% endblock %}</title> 

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/freelancer.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}" />



    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

  </head>


  <body id="page-top" class="index">
    <nav class="navbar navbar-default navbar-fixed-to-top">
      <div class='container-fluid'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'accueil' %}">
            <img alt="Brand" src="{% static "img/quick-pharma-logo.png" %}" height="120%" width="30px"/>
          </a>
        </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <!--<li><a href="#">Carte</a></li>-->
              <li><a href="{% url 'medicaments:liste-publique' %}">Medicaments</a></li>
              <li class="disabled"><a href="#">Carte</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method='GET' action="{% url 'haystack_search' %}">
              <div class="form-group">
                <input class="form-control" type="text" name='q' placeholder="Search">
              </div>
              <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-search"></span></button>
            </form>
            <ul class="nav navbar-nav navbar-right">
              <!--li><a href="#">Link</a></li>-->
              {% if request.user.is_authenticated %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mon Compte <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li class="text-center"><a href="{% url 'medicaments:ajouter' %}">Ajouter des Medicaments</a></li>
                  <li class="text-center"><a href="{% url 'medicaments:inventaire' %}">inventaire</a></li>
                  <li class="text-center"><a href="">Gestion du compte</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="text-center"><a href="https://medoc.herokuapp.com">Aller a MeDOC</a></li>
                  <li class="text-center"><a href="{% url 'accounts:logout' %}">Se deconnecter</a></li>
                </ul>
              </li>
              {% else %}
              <li><a href="{% url 'accounts:login' %}">Login</a></li>
              {% endif %}
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      {% block content %}
      {% endblock %}

      <!-- Footer -->

      <div class="scroll-top page-scroll visible-xs visible-sm">
          <a class="btn btn-primary" href="#page-top">
              <i class="fa fa-chevron-up"></i>
          </a>
      </div>
  </body>


      <!-- jQuery -->
      <script src="{% static 'js/jquery.js' %}"></script>

      <!-- Bootstrap Core JavaScript -->
      <script src="{% static 'js/bootstrap.min.js' %}"></script>

templates/medicaments/med_create.html
{% extends 'medicaments/med_base.html' %}

{% load crispy_forms_tags %}

{% block content %}

  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <span {% if message.tags %} class="label label-success" {% endif %}>{{ message }}</span>
      {% endfor %}
    </ul>
  {% endif %}

   <div class="col-sm-4 col-sm-offset-3">
     <form class="form-horizontal form-control-static" method='POST' action="{{ action_url }}">
       {% csrf_token %}{{ form|crispy }}
       <button class="btn btn-primary" type="submit">Ajouter Medicament</button>
     </form>
      <div class="well well-sm"><p> Les champs marques d'un '*' sont obligatoires </p></div>
   </div>

{% endblock %}

templates/medicaments/med_detail.html
{% extends 'medicaments/med_base.html' %}
{% load staticfiles %}

{% block content %}
<div class='page-header'>
	<h1>{{ medicament.commercial }} <small>pharmacie: {{ medicament.user }} </small> </h1>
</div>
	<div class="=panel panel-primary">
		<div class="media">
			<div class="media-left media-middle">
				<a href="#">
					{% if medicament.image %}
						<img class="media-object" src="{{ medicament.image }}" alt="">
						{% else %}
						<img class="media-object" src="{% static 'img/quick-pharma64.png' %}" alt="">
						{% endif %}
					</a>
			</div>

			<div class="media-body">
				<h4 class="media-header"> Nom commercial: {{ mediament.commercial }} </h4>
				<p>Nom generique: {{ medicament.generique }}</p>
				<p>Pharmacie: {{ medicament.user }} </p>
					{% if not medicament.famille %}
		  			<p>Famille : Aucune declaree</p>
					{% else %}
						<p>Famille : {{ medicament.famille }} </p>
					{% endif %}
						<p>Verifie: {{ medicament.last_seen|date:"DATETIME_FORMAT" }} {{ medicament.last_seen|time:"H:i" }}</p>
			</div>
		</div>
	</div>




{% endblock %}

templates/medicaments/med_update.html
{% extends 'medicaments/med_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
   <div class="col-sm-4 col-sm-offset-3">
     <form class="form-horizontal form-control-static" method='POST' action="">
       {% csrf_token %}{{ form|crispy }}
       <button class="btn btn-primary" type="submit">Modifier Medicament</button>
     </form>
     {% if messages %}
     <ul class="messages">
       {% for message in messages %}
       <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
       {% endfor %}
     </ul>
     {% endif %}
      <div class="well well-sm"><p> Les champs marques d'un '*' sont obligatoires </p></div>
   </div>
{% endblock %}

templates/medicaments/medicament_confirm_delete.html
{% extends 'medicaments/med_base.html' %}
{% load i18n %}

{% block content %}
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <form action="" method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete "{{ object }}"?</p>
      <input type="submit" value="Confirm" />
    </form>
  </div>
</div>
{% endblock %}

templates/medicaments/private_list.html
{% extends 'medicaments/med_base.html' %}



{% block content %}
	{% for medicament in queryset %}
		<div class="panel panel-default">
			<div class="panel-heading">Medicament {{ forloop.counter }}</div>
			<div class="panel-body">
			</div>

			<table class="table">
				<tr>
					<th> Nom commercial </th>
					<th> Derniere m.a.j </th>
					<th> pharmacie </th>
				<tr>
				  <td>
						<a href="{{ medicament.get_absolute_url }}">{{medicament.commercial}}</a>
					</td>
				  <td>{{medicament.verified|timesince}}</td>
					<td>{{medicament.user}}</td>
					<td>
						<a class="btn btn-primary" href="{{ medicament.get_modification_url }}"> Modifier </a>
						<a class="btn btn-danger" href="{{ medicament.get_deletion_url }}"> Supprimer </a>
					</td>
			  </tr>
			</table>

		</div>
	{% empty %}
		<p> Aucun Medicament </P>
	{% endfor %}

{% endblock %}

templates/medicaments/public_list.html
{% extends 'medicaments/med_base.html' %}



{% block content %}
		<div class="panel panel-default">
			<div class="panel-heading">Liste de medicaments </div>
			<div class="panel-body">
			</div>
			<table class="table">
				<tr>
					<th> Nom Generique </th>
					<th> Derniere m.a.j </th>
					<th> pharmacie </th>
				</tr>
				{% for medicament in queryset %}
					<tr>
				  	<td>{{forloop.counter}}-<a href="{{ medicament.get_absolute_url }}">{{medicament.generique}}</a></td>
				  	<td>{{medicament.verified|timesince}} ago</td>
						<td>{{medicament.user}}</td>
			  	</tr>
				{% empty %}
					<tr>
						<td> Rien </td>
						<td> Rien </td>
						<td> Rien </td>
					</tr>
				{% endfor %}
			</table>
		</div>
		<div class="pagination">
			<span class="step-links">
				{% if queryset.has_previous %}
					<a href="?page={{ queryset.previous_page_number}}">previous</a>
				{% endif %}
				<span class="current">
            Page {{ queryset.number }} of {{ queryset.paginator.num_pages }}.
        </span>

        {% if queryset.has_next %}
            <a href="?page={{ queryset.next_page_number }}">next</a>
        {% endif %}

{% endblock %}

templates/medicaments/results.html
{% extends 'medicaments/med_base.html' %}

{% if query %}

  <h3> Resultats </h3>

  {% for results in page.object_list %}

    {% if result.model_name == 'Medicament' %}
      <h4> <a href="{{ result.object.get_absolute_url }}">{{ result.object.commercial }}:</a>
        <p>{{ result.object.generique }}</p>
        <p>{{ result.object.description }}</p>
      </h4>
    {% elif result.model_name == 'Compagnie' %}
      <h4> <a href="{{ result.object.get_absolute_url }}">{{ result.object.nom }}:</a>
        <p>{{ result.object.pays }}</p>
      </h4>
    {% elif result.model_name == 'Famille' %}
      <h4> <a href="{{ result.object.get_absolute_url }}">{{ result.object.nom }}:</a>
        <p>{{ result.object.description }}</p>
      </h4>
    {% endif %}

  {% endfor %}

{% endif %}